### ISSUE TITLE
Blinky example fails compilation in mbed-drivers/platform.h:26:19: fatal error: cstddef: No such file or directory error

### ISSUE THREAD

**Issue by bitbangr** [drewcassidy/target-OSHChip-gcc#2]
I've purchased and OSHChip and programmer.  

1) installed the latest mbed dev environment and followed your example in the read README.md file. 
2) I created a blinky project , 
3) targeted the OSHChip and 
4) installed the mbed-drivers.
5) Then I cut and pasted the example project code into source\blinky.c  

Then I ran yotta build which fails with the following error:

---

[125/126] Building C object source/CMakeFiles/blinky.dir/Users/mj/Documents/VHS/oshchip/blinky/source/blinky.c.o
FAILED: /usr/local/bin/arm-none-eabi-gcc  -DYOTTA_MODULE_NAME=blinky -Dblinky_EXPORTS -Igenerated/include -I/Users/mj/Documents/VHS/oshchip/blinky -I/Users/mj/Documents/VHS/oshchip/blinky/yotta_modules/mbed-drivers -...
...
[ lots of deleted log stuff here ]
...
/Users/mj/Documents/VHS/oshchip/blinky/source/blinky.c
In file included from /Users/mj/Documents/VHS/oshchip/blinky/yotta_modules/mbed-drivers/mbed-drivers/mbed.h:22:0,
                 from /Users/mj/Documents/VHS/oshchip/blinky/source/blinky.c:1:
/Users/mj/Documents/VHS/oshchip/blinky/yotta_modules/mbed-drivers/mbed-drivers/platform.h:26:19: fatal error: cstddef: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
error: command ['ninja'] failed

---

It appears that the file platform.h cannot find "cstddef"

I've attached a text file with the complete terminal session from step one above which contains the full log of results each of the yotta steps. 

[OSHChipGCC_ExampleErrCompile.txt](https://github.com/OSHChip/target-OSHChip-gcc/files/183142/OSHChipGCC_ExampleErrCompile.txt)

Hi I'm new to both mbed dev AND OSHChip so please excuse me if I have made some obvious mistake.

**Comment by drewcassidy** [comment]
The blinky example is in c++, not c. I'll add a note to the readme

**Comment by bitbangr** [comment]
Doh! Renamed to source file to blinky.cpp and compiles now.

Thanks
